using System.Diagnostics.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Testing;

namespace mawkgen.test;

public class UnitTest1
{
    [Fact]
    public async Task MawkGenTest()
    {
        var test = new CSharpSourceGeneratorTest<MawkGen, DefaultVerifier>
        {
            TestCode = /*lang=C#*/""""
                using mawkgen;

                interface I;

                namespace abc
                {
                    namespace def
                    {
                        [Mawk(awk)]
                        partial class Awk
                        {
                            #region awk
                            partial class A;
                            partial class B;
                            partial class C;
                            #endregion awk
                            const string awk = """
                            /#region awk/,/#endregion awk/ {
                                if (match($0, /partial class/))
                                    print substr($0, 0, RSTART - 1) "public partial class " substr($3, 0, length($3)-1) " : I;"
                            }
                            """;
                        }
                    }
                }
                """",
        };

        void Expect(string name, [StringSyntax("C#")] string code) => test.TestState.GeneratedSources.Add((typeof(MawkGen), name, code));
        /*
        Expect("Microsoft.CodeAnalysis.EmbeddedAttribute.cs", """
            // <auto-generated/>
            namespace Microsoft.CodeAnalysis
            {
                internal sealed partial class EmbeddedAttribute : global::System.Attribute
                {
                }
            }
            """);
        */
        Expect("mawkgen.g.cs", """
            namespace mawkgen;
            //[Microsoft.CodeAnalysis.Embedded]//todo: sdk net10 분석기 4.14.0~ 부터 사용가능
            class MawkAttribute(string awk) : System.Attribute;
            """);

        Expect("abc.def.Awk0.g.cs", """
            namespace abc
            {
                namespace def
                {
                    partial class Awk
                    {
                        
                        public partial class A : I;
                        public partial class B : I;
                        public partial class C : I;

                    }
                }
            }
            """);

        await test.RunAsync();
    }
}
